### ISSUE TITLE
About the hardware requirements

### ISSUE THREAD

**Issue by Pefect96** [adarobustness/adaptation_robustness#1]
Great job!  I want to know what are the computing resources required for this experiment? And training time?

**Comment by adarobustness** [comment]
Hi, thanks for your issue! There are two computation scenarios used in this study, model adaptations and model inference. 

For the adaptation, at least one GPU with 40GB memory is required to reproduce the results. We have released the adapted model checkpoints in the README which may save some efforts. The training time may vary given different adaptation methods and language models. To name one example, it costs approximately 40 hours to fullly fine-tune a CLIP-T5 in a multi-task setting on a A100 GPU with 40 GB memory. 

For the inference, one GPU with 16GB memory should be enough to run one single inference experiment.
